### ISSUE TITLE
Goldfeld-Quandt vs. White or Breusch-Pagan

### ISSUE THREAD

**Issue by minotaur142** [learn-co-curriculum/dsc-ols-regression-diagnostics#1]
In both of my econometrics textbooks the goldfeld-quandt is considered an inferior test for heteroskedasticity to its more modern counterparts, the Breusch Pagan and White tests, both of which are available in statsmodels

**Comment by mas16** [comment]
Thanks minotaur142. The text has been updated to mention the other tests.
